export const FETCH_POST = 'POST/FETCH_POST';
export const FETCH_POST_SUCCESS = 'POST/FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'POST/FETCH_POST_FAIL';

export const REFRESH_DATA = 'POST/REFRESH_DATA';
export const REFRESH_DATA_SUCCESS = 'POST/REFRESH_DATA_SUCCESS';
export const REFRESH_DATA_FAIL = 'POST/REFRESH_DATA_FAIL';
