export const FETCH_USER = 'PROFILE/FETCH_USER';
export const FETCH_USER_SUCCESS = 'PROFILE/FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'PROFILE/FETCH_USER_FAIL';

export const REFRESH_DATA = 'PROFILE/REFRESH_DATA';
export const REFRESH_DATA_SUCCESS = 'PROFILE/REFRESH_DATA_SUCCESS';
export const REFRESH_DATA_FAIL = 'PROFILE/REFRESH_DATA_FAIL';
