export const FETCH_NEWS = 'NEWS/FETCH_NEWS';
export const FETCH_NEWS_SUCCESS = 'NEWS/FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'NEWS/FETCH_NEWS_FAIL';

export const REFRESH_DATA = 'NEWS/REFRESH_DATA';
export const REFRESH_DATA_SUCCESS = 'NEWS/REFRESH_DATA_SUCCESS';
export const REFRESH_DATA_FAIL = 'NEWS/REFRESH_DATA_FAIL';
